Repository guangliang2019/Proto-UI, pull requests merged in 2025-04, with the labels that each got.

#97 更新了介绍文档
  src/components/prototype/switch/index.ts
  src/components/prototype/switch/interface.ts
  src/components/prototype/switch/switch.ts
  src/components/shadcn/button/button.ts
  src/components/shadcn/select/anatomy.json
  src/components/shadcn/select/select-arrow.ts
  src/components/shadcn/select/select-check.ts
  src/components/shadcn/select/select-content.ts
  src/components/shadcn/select/select-item.ts
  src/components/shadcn/select/select-trigger.ts
  src/core/behaviors/as-select/select-content.ts
  src/www/app/app.ts
  src/www/app/components/prototype/prototype-docs.ts
  src/www/app/docs/index.ts
  src/www/app/docs/introduction.ts
  src/www/app/docs/pdsl.ts
  src/www/app/docs/quick-start.ts
  src/www/components/doc-component/doc-component.ts
  src/www/components/doc-component/doc-section/markdown.ts
  src/www/router/index.json
Labels: documentation, enhancement

#98 docs: 更新了 examples 的引用
  src/components/prototype/select/anatomy.json
  src/examples/mail/index.html
  src/www/app/examples/examples.ts
  src/www/components/website-nav/website-nav.ts
Labels: documentation

#100 card组件
  src/components/shadcn/card/card-content.ts
  src/components/shadcn/card/card-description.ts
  src/components/shadcn/card/card-footer.ts
  src/components/shadcn/card/card-header.ts
  src/components/shadcn/card/card-title.ts
  src/components/shadcn/card/card.ts
  src/components/shadcn/card/index.ts
  src/components/shadcn/card/style.css
  src/components/shadcn/index.ts
  src/www/app/components/shadcn/card/card-basic.ts
  src/www/app/components/shadcn/card/card.ts
  src/www/app/components/shadcn/card/index.ts
  src/www/app/components/shadcn/index.ts
  src/www/app/components/shadcn/shadcn-docs.ts
  src/www/router/index.json
Labels: enhancement, good first issue

#101 feat: transition 组件
  src/components/shadcn/select/interface.ts
  src/components/shadcn/select/select-content.ts
  src/components/shadcn/select/style.css
  src/core/behaviors/as-select/select-content.ts
  src/core/behaviors/as-select/select-trigger.ts
  src/core/behaviors/as-transition/as-transition-child.ts
  src/core/behaviors/as-transition/as-transition.ts
  src/core/behaviors/as-transition/index.ts
  src/core/behaviors/as-transition/interface.ts
Labels: enhancement

#102 fix: 修复 overlay 的 click outside 逻辑问题
  src/core/behaviors/as-overlay/as-overlay.ts
  src/core/behaviors/as-select/select-content.ts
Labels: bug

#103 fix: 修复 overlay 的 click outside 逻辑问题
  src/core/behaviors/as-overlay/as-overlay.ts
Labels: bug

#105 开始尝试编写checkbox
  src/components/prototype/checkbox/index.ts
  src/components/prototype/index.ts
  src/core/behaviors/as-checkbox/as-checkbox-indicator.ts
  src/core/behaviors/as-checkbox/as-checkbox.ts
  src/core/behaviors/as-checkbox/index.ts
  src/core/behaviors/as-checkbox/interface.ts
  src/www/app/components/prototype/checkbox/checkbox-basic.ts
  src/www/app/components/prototype/checkbox/checkbox.ts
  src/www/app/components/prototype/checkbox/index.ts
  src/www/app/components/prototype/prototype-docs.ts
  src/www/router/index.json
Labels: enhancement

#106 编写了shadcncheckbox
  src/components/shadcn/checkbox/checkbox-indicator.ts
  src/components/shadcn/checkbox/checkbox.ts
  src/components/shadcn/checkbox/index.ts
  src/components/shadcn/checkbox/interface.ts
  src/components/shadcn/checkbox/style.css
  src/components/shadcn/index.ts
  src/components/shadcn/switch/style.css
  src/www/app/components/shadcn/checkbox/checkbox-basic.ts
  src/www/app/components/shadcn/checkbox/checkbox.ts
  src/www/app/components/shadcn/checkbox/index.ts
  src/www/app/components/shadcn/index.ts
  src/www/app/components/shadcn/shadcn-docs.ts
  src/www/router/index.json
  src/www/utils/tailwind.ts
  yarn.lock
Labels: enhancement
