Repository guangliang2019/Proto-UI, pull requests merged in 2025-03, with the labels that each got.

#85 feat: 重构 tab 进行中
  src/components/common/overlay/overlay.ts
  src/components/prototype/button/button.ts
  src/components/prototype/button/index.ts
  src/components/prototype/index.ts
  src/components/prototype/select/index.ts
  src/components/prototype/select/interface.ts
  src/components/prototype/select/select-content.ts
  src/components/prototype/select/select-item.ts
  src/components/prototype/select/select-trigger.ts
  src/components/prototype/select/select-value.ts
  src/components/prototype/select/select.ts
  src/components/prototype/test-tab/test-tab-trigger.ts
  src/components/shadcn/button/button.ts
  src/components/shadcn/button/interface.ts
  src/core/adapter/web-component.ts
  src/core/components/button/button.ts
  src/core/components/button/index.ts
  src/core/components/button/interface.ts
  src/core/components/overlay/index.ts
  src/core/components/overlay/interface.ts
  src/core/components/overlay/overlay.ts
  src/core/components/select/index.ts
  src/core/components/select/interface.ts
  src/core/components/select/select-content.ts
  src/core/components/select/select-item.ts
  src/core/components/select/select-trigger.ts
  src/core/components/select/select-value.ts
  src/core/components/select/select.ts
  src/core/components/tabs/interface.ts
  src/core/components/tabs/tabs-content.ts
  src/core/components/tabs/tabs-indicator.ts
  src/core/components/tabs/tabs-trigger.ts
  src/core/components/tabs/tabs.ts
  src/core/components/trigger/index.ts
  src/core/components/trigger/trigger.ts
  src/core/constants.ts
  src/core/context.ts
  src/core/define-prototype.ts
  src/core/hooks/as-overlay.ts
  src/core/hooks/use-click-outside.ts
  src/core/hooks/use-event-listener.ts
  src/core/interface.ts
  src/core/lifecycle.ts
  src/core/render.ts
  src/core/utils/dom.ts
  src/www/app/components/prototype/prototype-docs.ts
  src/www/app/components/prototype/radio-group/radio-group-basic.ts
  src/www/app/components/prototype/select/select-basic.ts
  src/www/app/components/prototype/select/select.ts
  src/www/app/components/prototype/test-tab/test-tab-basic.ts
  src/www/app/components/shadcn/shadcn-docs.ts
Labels: enhancement

#87 feat: 内核大重构
  docs/issues/001-props-attributes-unification.md
  docs/issues/002-lifecycle-safety.md
  package-lock.json
  package.json
  src/components/prototype/test-button/test-button.ts
  src/core/interface.ts
  src/next-core/README.md
  src/next-core/adapter/README.md
  src/next-core/adapter/context.ts
  src/next-core/adapter/interface.ts
  src/next-core/adapter/props.ts
  src/next-core/adapter/web-component/index.ts
  src/next-core/adapter/web-component/managers/attribute.ts
  src/next-core/adapter/web-component/managers/index.ts
  src/next-core/adapter/web-component/managers/lifecycle.ts
  src/next-core/adapter/web-component/managers/props.ts
  src/next-core/adapter/web-component/managers/render.ts
  src/next-core/adapter/web-component/managers/state.ts
  src/next-core/behaviors/as-button.ts
  src/next-core/hooks/use-event-listener.ts
  src/next-core/index.ts
  src/next-core/interface.ts
  src/next-core/shared/types.ts
  src/next-core/utils/naming.ts
  src/www/app/components/prototype/test-button/test-button-basic.ts
  yarn.lock
Labels: enhancement

#89 feat: 内核重构收尾 + 文档完善
  docs/contribute/00-introduction.md
  docs/contribute/01-prototype.md
  docs/contribute/02-adapter.md
  docs/contribute/03-hooks.md
  docs/contribute/04-managers.md
  docs/contribute/99-others.md
  src/components/prototype/test-button/test-button.ts
  src/next-core/adapter/interface.ts
  src/next-core/adapter/web-component/index.ts
  src/next-core/adapter/web-component/managers/event.ts
  src/next-core/adapter/web-component/managers/index.ts
  src/next-core/behaviors/as-button.ts
  src/next-core/interface.ts
  src/next-core/utils/component.ts
Labels: documentation, enhancement, hard

#90 feat: 渲染器逻辑
  src/next-core/adapter/context.ts
  src/next-core/adapter/props.ts
  src/next-core/adapter/renderer.ts
  src/next-core/adapter/web-component/index.ts
  src/next-core/adapter/web-component/managers/attribute.ts
  src/next-core/adapter/web-component/managers/event.ts
  src/next-core/adapter/web-component/managers/lifecycle.ts
  src/next-core/adapter/web-component/managers/props.ts
  src/next-core/adapter/web-component/managers/render.ts
  src/next-core/adapter/web-component/managers/state.ts
  src/next-core/adapter/web-component/renderer.ts
  src/next-core/behaviors/as-button.ts
  src/next-core/index.ts
  src/next-core/interface/component.ts
  src/next-core/interface/index.ts
  src/next-core/interface/managers.ts
  src/next-core/interface/props.ts
  src/next-core/interface/prototype.ts
  src/next-core/interface/renderer.ts
Labels: enhancement, hard

#92 feat: next-core context
  docs/contribute/05-contribute.md
  src/next-core/adapter/context.ts
  src/next-core/adapter/web-component/index.ts
  src/next-core/adapter/web-component/managers/context.ts
  src/next-core/behaviors/as-button.ts
  src/next-core/behaviors/as-tabs/as-tabs-content.ts
  src/next-core/behaviors/as-tabs/as-tabs-trigger.ts
  src/next-core/behaviors/as-tabs/as-tabs.ts
  src/next-core/behaviors/as-tabs/index.ts
  src/next-core/behaviors/as-tabs/interface.ts
  src/next-core/interface/component.ts
  src/next-core/interface/managers.ts
  src/next-core/interface/prototype.ts
  src/next-core/utils/component.ts
Labels: documentation, enhancement

#91 初步编写了switch组件的内核
  dev-cli/command/add-component.cjs
  package-lock.json
  src/components/prototype/index.ts
  src/components/prototype/new-switch/index.ts
  src/core/components/switch/index.ts
  src/core/components/switch/interface.ts
  src/core/components/switch/switch.ts
  src/www/app/components/prototype/new-switch/index.ts
  src/www/app/components/prototype/new-switch/new-switch-basic.ts
  src/www/app/components/prototype/new-switch/new-switch.ts
  src/www/app/components/prototype/prototype-docs.ts
  src/www/app/components/prototype/select/index.ts
  src/www/app/components/prototype/select/select.ts
  src/www/router/index.json
  yarn.lock
Labels: enhancement, good first issue

#93 feat: 新内核就绪
  MANIFEST/00-USER.md
  MANIFEST/01-广亮-Lynn.md
  MANIFEST/README.md
  docs/contribute/05-contribute.md
  src/components/prototype/button/index.ts
  src/components/prototype/test-button/test-button.ts
  src/components/prototype/test-tab/test-tab-content.ts
  src/components/prototype/test-tab/test-tab-trigger.ts
  src/components/prototype/test-tab/test-tab.ts
  src/components/shadcn/button/button.ts
  src/next-core/adapter/context.ts
  src/next-core/adapter/web-component/commands/event.ts
  src/next-core/adapter/web-component/index.ts
  src/next-core/adapter/web-component/managers/context.ts
  src/next-core/adapter/web-component/managers/event.ts
  src/next-core/adapter/web-component/managers/props.ts
  src/next-core/behaviors/as-button.ts
  src/next-core/behaviors/as-button/as-button.ts
  src/next-core/behaviors/as-button/index.ts
  src/next-core/behaviors/as-button/interface.ts
  src/next-core/behaviors/as-tabs/as-tabs-content.ts
  src/next-core/behaviors/as-tabs/as-tabs-trigger.ts
  src/next-core/behaviors/as-tabs/as-tabs.ts
  src/next-core/behaviors/as-tabs/interface.ts
  src/next-core/index.ts
  src/next-core/interface/component.ts
  src/next-core/interface/element.ts
  src/next-core/interface/event.ts
  src/next-core/interface/managers.ts
  src/next-core/interface/prototype.ts
  src/next-core/shared/types.ts
  src/next-core/utils/search.ts
Labels: enhancement, hard
